# Tensorflow Basics

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


## Declaring Variables & Constants

### Constants

In [2]:
# Create a constant tensor
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# number of dimensions
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
# create a matrix
matrix = tf.constant([
    [10, 7],
    [19, 91]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [19, 91]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# create matrix with different data type
another_matrix = tf.constant([
    [10., 7.],
    [4., 7.],
    [1., 2.]
], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 4.,  7.],
       [ 1.,  2.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# create a tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

### Variables

In [13]:
# create a variable and constant tensor
changeable_variable = tf.Variable([10, 7])
unchangeable_variable = tf.constant([10, 7])

changeable_variable, unchangeable_variable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# change an element in variable tensor
changeable_variable[0].assign(7)
changeable_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# change an element in variable tensor
unchangeable_variable[0].assign(7)
unchangeable_variable

AttributeError: ignored

### Random Tensors

In [16]:
tf.random.uniform(shape=(3, 3), seed=42) # from an uniform distribution

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.95227146, 0.67740774, 0.79531825],
       [0.75578177, 0.4759556 , 0.6310148 ],
       [0.18602037, 0.11430776, 0.3362218 ]], dtype=float32)>

In [17]:
tf.random.normal(shape=(3, 3), seed=42) # from an normal distribution

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.28077507, -0.1377521 , -0.6763296 ],
       [ 0.02458041, -0.89358455, -0.82847327],
       [ 1.2068944 ,  1.3810157 , -1.4557977 ]], dtype=float32)>

### Shuffle A Tensor

In [18]:
unshuffled_tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
unshuffled_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [19]:
tf.random.shuffle(unshuffled_tensor, seed=12)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

### Seeds In Tensorflow

In [20]:
# setting a global seed
tf.random.set_seed(13)

In [21]:
# generates different numbers everytime, but uniform across runs
tf.random.uniform([1]), tf.random.uniform([1])

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.5983684], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.53933334], dtype=float32)>)

### Ones And Zeros

In [22]:
tf.ones(shape=(4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros(shape=(4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### With Numpy

In [24]:
import numpy as np

In [25]:
numpy_arr = np.arange(1, 25)

In [26]:
tf.constant(numpy_arr, shape=(4, 3, 2))

<tf.Tensor: shape=(4, 3, 2), dtype=int64, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])>

## Getting Information From Tensors

### Getting Dimensions, Data Types, Shape & Size

In [27]:
rank_4_tensor = tf.zeros(shape=(4, 4, 4, 4))
rank_4_tensor

<tf.Tensor: shape=(4, 4, 4, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
        

In [28]:
rank_4_tensor.dtype # data types

tf.float32

In [29]:
rank_4_tensor.ndim # dimensions

4

In [30]:
tf.shape(rank_4_tensor) # shape

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 4, 4, 4], dtype=int32)>

In [31]:
tf.size(rank_4_tensor) # size

<tf.Tensor: shape=(), dtype=int32, numpy=256>

### Indexing Tensors

In [32]:
rank_3_tensor_elements = np.arange(0, 27)

In [33]:
rank_3_tensor = tf.constant(rank_3_tensor_elements, shape=(3, 3, 3))

In [34]:
rank_3_tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])>

In [35]:
rank_3_tensor[1, 1, 1] # get a specific element

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [36]:
rank_3_tensor[-1, :, :]

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])>

## Operations On Tensors

### Expandng Dimensions

In [37]:
rank_3_tensor[..., tf.newaxis]

<tf.Tensor: shape=(3, 3, 3, 1), dtype=int64, numpy=
array([[[[ 0],
         [ 1],
         [ 2]],

        [[ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8]]],


       [[[ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14]],

        [[15],
         [16],
         [17]]],


       [[[18],
         [19],
         [20]],

        [[21],
         [22],
         [23]],

        [[24],
         [25],
         [26]]]])>

In [38]:
tf.expand_dims(rank_3_tensor, -1)

<tf.Tensor: shape=(3, 3, 3, 1), dtype=int64, numpy=
array([[[[ 0],
         [ 1],
         [ 2]],

        [[ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8]]],


       [[[ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14]],

        [[15],
         [16],
         [17]]],


       [[[18],
         [19],
         [20]],

        [[21],
         [22],
         [23]],

        [[24],
         [25],
         [26]]]])>

### Reshaping Tensors

In [39]:
tensor_ones = tf.ones(shape=(5, 2))
tensor_ones

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [40]:
tf.reshape(tensor_ones, shape=(2, 5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

### Transpose A Tensor

In [41]:
tensor_ex0 = tf.constant([[1, 2], [3, 4], [5,6]])
tensor_ex0

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [42]:
tf.transpose(tensor_ex0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

### Manipulating Tensors

In [43]:
tensor_ex1 = tf.constant([[1, 2], [3, 4]])

In [44]:
tensor_ex1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [45]:
tf.add(tensor_ex1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

### Matrix Multiplication

In [46]:
tensor_ex2 = tf.random.normal(shape=(2, 2))
tensor_ex3 = tf.random.normal(shape=(2, 2))

tensor_ex2, tensor_ex3

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.9487271 ,  1.3044667 ],
        [-1.1531727 , -0.28560743]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-0.1856016, -1.1418061],
        [ 0.0194767, -2.7855177]], dtype=float32)>)

In [47]:
tf.matmul(tensor_ex2, tensor_ex3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.20149197, -2.550353  ],
       [ 0.20846802,  2.1122642 ]], dtype=float32)>

### Changing Data Types

In [49]:
tensor_ex3 = tf.random.normal(shape=(2, 2))
tensor_ex3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.4116935 ,  0.1200662 ],
       [-0.72520065, -1.0911381 ]], dtype=float32)>

In [50]:
tf.cast(tensor_ex3, tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[-1.412  ,  0.12006],
       [-0.725  , -1.091  ]], dtype=float16)>

## Aggregation Of Tensors

### Getting Absolute, Minimum, Maximum, Mean, Sum, Variance and Standard Deviation Of A Tensor

In [52]:
tensor_ex4 = tf.random.normal(shape=(3, 3))
tensor_ex4

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5971814 , -0.99537617,  1.035538  ],
       [ 0.02057712, -0.12836641, -0.9310614 ],
       [-1.7767631 , -1.466424  ,  0.08939307]], dtype=float32)>

In [55]:
tf.abs(tensor_ex4) # absolute values

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.5971814 , 0.99537617, 1.035538  ],
       [0.02057712, 0.12836641, 0.9310614 ],
       [1.7767631 , 1.466424  , 0.08939307]], dtype=float32)>

In [58]:
tf.reduce_min(tensor_ex4) # minimum

<tf.Tensor: shape=(), dtype=float32, numpy=-1.7767631>

In [59]:
tf.reduce_max(tensor_ex4) # maximum

<tf.Tensor: shape=(), dtype=float32, numpy=1.035538>

In [60]:
tf.reduce_mean(tensor_ex4) # mean

<tf.Tensor: shape=(), dtype=float32, numpy=-0.5277405>

In [66]:
tf.reduce_sum(tensor_ex4) # sum

<tf.Tensor: shape=(), dtype=float32, numpy=-4.7496643>

In [64]:
tf.math.reduce_variance(tensor_ex4) # variance

<tf.Tensor: shape=(), dtype=float32, numpy=0.67913365>

In [65]:
tf.math.reduce_std(tensor_ex4) # standard deviation

<tf.Tensor: shape=(), dtype=float32, numpy=0.82409567>