# Tensorflow Basics

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.2


## Constants

In [4]:
# Create a constant tensor
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# number of dimensions
scalar.ndim

0

In [7]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
 vector.ndim

1

In [10]:
# create a matrix
matrix = tf.constant([
    [10, 7],
    [19, 91]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [19, 91]], dtype=int32)>

In [11]:
matrix.ndim

2

In [15]:
# create matrix with different data type
another_matrix = tf.constant([
    [10., 7.],
    [4., 7.],
    [1., 2.]
], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 4.,  7.],
       [ 1.,  2.]], dtype=float16)>

In [14]:
another_matrix.ndim

2

In [16]:
# create a tensor
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
tensor.ndim

3

## Variables

In [20]:
# create a variable and constant tensor
changeable_variable = tf.Variable([10, 7])
unchangeable_variable = tf.constant([10, 7])

changeable_variable, unchangeable_variable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [22]:
# change an element in variable tensor
changeable_variable[0].assign(7)
changeable_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [23]:
# change an element in variable tensor
unchangeable_variable[0].assign(7)
unchangeable_variable

AttributeError: ignored