# Checking How Seeds And Random Numbers Work In Tensorflow

In [1]:
import tensorflow as tf

## Without Global Seed

### Random Normal Tensors Without Seeds

This just generates random tensors everytime, even when runtime is restarted

In [2]:
tf.random.normal(shape=(2, 2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.63207924, -0.71137315],
       [ 1.1874416 ,  0.5057532 ]], dtype=float32)>

### Random Stateless Normal Tensors With Seeds

This generates random tensors, however, having same seed generates the same tensors

In [3]:
tf.random.stateless_normal(shape=(2, 2), seed=[10,10])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.3279768 ,  0.34494457],
       [-0.6404196 ,  0.19267617]], dtype=float32)>

### Random Normal Tensors, With Seed

This generates the same sequence of random tensors, which is the same across runs

In [4]:
tf.random.normal(shape=(2, 2), seed=12)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.43663138,  0.8449775 ],
       [-0.01180986, -0.8844008 ]], dtype=float32)>

## With Global Seed

### Random Tensors Without Seeds


This generates the same sequence of random tensors, which is same across runs

In [5]:
tf.random.set_seed(42)

In [6]:
tf.random.normal(shape=(2, 2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258],
       [ 0.3194337, -1.4075519]], dtype=float32)>

### Random Stateless Normal Tensors With Seeds

This is uneffected by global seed, has the same output as without global seed

In [7]:
tf.random.stateless_normal(shape=(2, 2), seed=[10,10])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.3279768 ,  0.34494457],
       [-0.6404196 ,  0.19267617]], dtype=float32)>

### Random Normal Tensors, With Seed

This produces the same sequence of random tensors across runs, however, is more deterministic 

In [9]:
tf.random.normal(shape=(2, 2), seed=42)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00720546,  0.41561252],
       [ 0.08735802,  0.21171632]], dtype=float32)>

## With Generator

This generates the same sequence of random tensors, however, you don't need to restart the notebook to get back the same tensors

In [18]:
rng = tf.random.Generator.from_seed(12)

In [19]:
rng.normal(shape=(2, 2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.0130816 ,  0.28291714],
       [ 1.2132233 ,  0.46988967]], dtype=float32)>

In [20]:
rng2 = tf.random.Generator.from_seed(12)

In [21]:
rng2.normal(shape=(2, 2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.0130816 ,  0.28291714],
       [ 1.2132233 ,  0.46988967]], dtype=float32)>