In [1]:
import numpy as np

#### Vector Rows

In [2]:
vector_row = np.array([1, 2, 3])

In [3]:
vector_row

array([1, 2, 3])

#### Vector Columns

In [4]:
vector_col = np.array([
    [1],
    [2],
    [3]
])

In [5]:
vector_col

array([[1],
       [2],
       [3]])

#### Matrices

In [6]:
matrix = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [7]:
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Sparse Matrix

In [8]:
from scipy import sparse

In [15]:
matrix = np.array([
    [0, 0, 0],
    [1, 0, 1],
    [0, 0, 3]
])

In [16]:
matrix_sparse = sparse.csr_matrix(matrix)

In [17]:
print(matrix_sparse)

  (1, 0)	1
  (1, 2)	1
  (2, 2)	3
