In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
array

array([[1, 2, 3],
       [4, 5, 6]])

#### Array Functions

In [2]:
np.arange(0.25, 100/6, 3.5)

array([ 0.25,  3.75,  7.25, 10.75, 14.25])

In [3]:
np.linspace(1, 20, 3)

array([ 1. , 10.5, 20. ])

#### Matrix Maultiplication

In [5]:
prices = np.array([[3, 7, 12, 18, 6], [3.6, 8.4, 14.4, 21.6, 7.2]])

In [6]:
prices

array([[ 3. ,  7. , 12. , 18. ,  6. ],
       [ 3.6,  8.4, 14.4, 21.6,  7.2]])

In [8]:
items = np.array([
    [0, 3, 6, 1, 0],
    [1, 6, 2, 0, 0],
    [23, 6, 8, 3, 5],
    [5, 7, 2, 9, 4],
    [3, 4, 1, 8, 7]
])

In [14]:
amounts = items.dot(prices.T)

In [30]:
np.linalg.inv(items).dot(amounts)

array([[ 3. ,  3.6],
       [ 7. ,  8.4],
       [12. , 14.4],
       [18. , 21.6],
       [ 6. ,  7.2]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])